### ISSUE TITLE
Doesn't work with OSX default getopt

### ISSUE THREAD

**Issue by kornysietsma** [labbots/google-drive-upload#12]
OSX comes with non-gnu versions of getopt, sed and stat, which cause this script to behave badly - help doesn't work, some commands do work, but it does things like create folders called `--options` in your drive!

You can work around this by running `brew install coreutils gnu-sed gnu-getopt`
and then following the instructions to put the gnu getopt in your path:
```
If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc
```
You'll also need to modify `upload.sh` to use `gstat` instead of `stat` and `gsed` instead of `sed`, unless you are willing to force your system to use gnu utils by default, as described in https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

**Comment by Narendra-WAL** [comment]
I made the changes as mentioned above. But still the file is not getting uploaded. Script is not able to find the fileName when this command is used 
`./upload.sh -v -r <google-folder-id> <file/directory-path>`

I have hardcoded the fileName in upload.sh. Then file is getting uploaded to a folder with name --options, rather than the desired folder. And I don't even have access to that --options folder. I am just able to see this newly uploaded file in 'Recent files'.

**Comment by robert7** [comment]
I use this script on linux and its very useful. Recently I tried on OSX (macOS 10.15) and ist dosesn't work, as few used utilities (getopt, stat and sed) which are per default available on OSX work a bit differently. 
Here is quick fix:
1, install gnu utilities `brew install coreutils gnu-sed gnu-getopt`
2, at the begin of tjhe upload.sh insert `PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"`

Then in works..
