### ISSUE TITLE
Keep a local docs in repo itself

### ISSUE THREAD

**Issue by Akianonymus** [labbots/google-drive-upload#168]
It's good and all that we have a seperate website to shows the docs, but i think we should have a local docs in the repo too.

So, we don't need to just clone another branch just to write docs and frankly it's tedious.

By docs i mean whatever was in readme previously.

And not in main readme but docs.md or something.

**Comment by Akianonymus** [comment]
@labbots

**Comment by dhiva** [comment]
@Akianonymus The docs are moved to different branch so that we could provide rich web documentation and not just in readme. This is done for few reasons.

1. Simple web documentation for users to use.
2. This provides better analytical data on the usage of the script through google analytics which is not possible with Github insights.
3. I do not want to maintain 2 sets of separate documentations. One in readme and one for the web documentation as this could lead to stale information. We need to have single source of truth.

The new branch is necessary so we could build the hugo docs into static website through Github actions. I don't see why it is difficult to update something in different branch. If you find it difficult, then you could create a worktree for hugo-docs branch while you are in master. This would eliminate the need to switch branches while you are working.
 
```
git worktree add -B hugo-docs hugo-docs origin/hugo-docs
cd hugo-docs/
```

Once you have updated the docs. you can create a commit and push to the `hugo-docs` branch from within the directory.

**Comment by Akianonymus** [comment]
> 1. Simple web documentation for users to use.

Fair point.

> 2. This provides better analytical data on the usage of the script through google analytics which is not possible with Github insights.

I don't see how this is relavant anyway, but whatever.

> 3. I do not want to maintain 2 sets of separate documentations. One in readme and one for the web documentation as this could lead to stale information. We need to have single source of truth.

You just need properly sub categorized docs in the main repo, then maintain your seperate branch to automatically fetch and update stuff, probably a little complex, but i cannot fathom that the documentation itself is not in the main repo.

When i clone the repo i except the docs to be there. Just residing fully on a external website is just ridiculous in my opinion.

Anyway, judging from your statement, you are in no mood to change this ( or i am wrong ). So, i apologise in advance because i am really not gonna take the hassle to update docs on a seperate branch ( mostly because of the hassle and time ) for my future contribution ( i know this is very arrogant, but ಠ︵ಠ ). I would obviously, still update the in-script docs.

**Comment by Akianonymus** [comment]
Btw, a little offtopic, could you add `hacktoberfest` tag to repo.

**Comment by dhiva** [comment]
@Akianonymus  Keeping document within repo might be your preference but I think having a web document is much more accessible and easier to navigate. Moreover the analytical data from google analytics is much more rich and it is not limited to few weeks insight shown in Github. I wonder why creating a worktree and using it would be difficult for you. The documents are still within the same repository and severed as static pages. I would not recommend you making changes without documentation update as that wouldn't be in the best interest of our users. I would like you to really try the worktree approach I mentioned in my previous comment before you jump to conclusions. 

Thanks for recommending the hacktoberfest. I will definitely add it to the repo. Thanks for bringing it up.

**Comment by Akianonymus** [comment]
Well, talking about difficulties, i have to create two prs everytime because docs and script are in different branch. 

My proposal was to keep the docs in the main repo, categorised and stuff, and website will be automatically built. Many projects actually do that, maybe i will try that in the near future.

Also, you if i am not wrong, you can also keep the docs in main branch and still built the website ? Just throwing ideas, Yes, i am just stuck at the part i have to create two PRs, haha.

Anyway, keeping that aside, you gotta update your docs for this commit https://github.com/labbots/google-drive-upload/commit/5295b76ca5d212fedc28db95b3c20b2c672c6736.

**Comment by labbots** [comment]
@Akianonymus you could push the changes to the docs directly to hugo-docs branch.
