### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#97]
Why "gupload *" doesn't upload all the files present in the directory? It only uploaded a single folder.

**Comment by Akianonymus** [comment]
@capriciousduck because 2nd arguments is taken as foldername. That's why it doesn't work.

But you can avoid this by 

```
gupload -f * -o
```

this will upload all files matched by the glob

Although i would love to remove this behaviour, that it takes 2nd argument as foldername, rather just use -C option only.
Using 2nd arg as foldername surely gets uncomfortable.

what do you think @labbots ? I propose on removing this behaviour, -C flag should be enough

**Comment by labbots** [comment]
@Akianonymus I am not sure what exactly you are proposing in the changes. Are you intending to remove `-f` option?

**Comment by Akianonymus** [comment]
@labbots Let me explain

currently by doing below command

`gupload test1 test2`

test1 is taken as file input and test2 is taken as gdrive folder input.

So, to change the behaviour that both test1 and test2 is takes as file input.

For specifying gdrive folder name, only -C  flag.

**Comment by Akianonymus** [comment]
I have applied the fixes.
